### PR TITLE
feat: added gcp_na region

### PR DESCRIPTION
**Pull request by abhinav-from-contentstack**
added support for gcp_na region

### CODE REVIEW

**Review by sunil-lakshman — COMMENTED** [review]
@abhinav-from-contentstack Can you update release version and changelog file.

**Comment by abhinav-from-contentstack** [comment]
Hi @sunil-lakshman , this repository does not maintain any CHANGELOG.md or version.
The packge manager picks this information directly from github release/tags.

**Review by sunil-lakshman — COMMENTED** [review]
Approved

**Review by aravindbuilt — APPROVED** [review]

**Review by sunil-lakshman — APPROVED** [review]
Approved

**Pull request merged**
